project:
  output-dir: docs
    
execute:
  echo: true
  freeze: false
  eval: false
  
book:  
  chapters:
    - index.qmd
    - part: "Methods"
      chapters:
      - Methods_Prokka_Annotations.qmd
      - Methods_ANIs.qmd
      - Methods_Phylogenies.qmd
      - Methods_Anvio.qmd
    - references.qmd
  
