---
title: "ANI explanation"
output: html_document
date: "2023-03-09"
---

Hello everyone, I am going to go over the average nucleotide identity matrix of the *Cornye tuberculostearicum complex* with some addition strains

It is a big image so I am going to try and break it down. I am going to start at the top right and go down to left diagonally.

**TURQUOISE BOX** - newly proposed novel species named C. marquesiae which are \~94% to C. tuberculostearicum. The 5 C. aurimucosum E's also fell within this group.

**BLUE BOX** - C. tuberculostearicum group, type strain boxed in black. Ctu_C, Ctu_D and C. sp900, and one MAG

**GREEN BOX** - foot clade, and one MAG here. It is still an unclassified species.

**PINK BOX -** C. curiae, Foot clade is 94% to it. An open question is do we still want to name the foot clade.

**DARK GREEN BOX -** Originally planned as C. savuti, but now match thenewly proposed novel species named C. yonathiae at 99%. One MAG here

Single MAG SMGC_38, that is alone and an unclassified species

**PURPLE BOX** - This is the largest group. Here isolates closely matched the genome named C. kefirresidentii which we plan to validly name as C. nasorum.

**BOTTOM LEFT -** genomes that did not clade into any groups
